server:
  port: 8081
  forward-headers-strategy: native

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${SPRING_CLOUD_EUREKA_HOST}:${SPRING_CLOUD_EUREKA_PORT}${SPRING_CLOUD_EUREKA_PATH}

spring:
  application:
    name: ${SPI_ADMIN_SERVICE_CLIENT_ID}
  datasource:
    url: ${DB_ADMIN_SERVICE_URL}
    username: ${DB_ADMIN_SERVICE_USERNAME}
    password: ${DB_ADMIN_SERVICE_PASSWORD}
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    hikari:
      pool-name: ConfigServiceHikariPool
      connection-test-query: SELECT 1
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
        cache:
          use_second_level_cache: false
  profiles:
    active: dev
  security:
    oauth2:
       #resourceserver:
        #jwt:
          #issuer-uri: ${SPI_URI_SERVER}
       client:
        registration:
          keycloak:
            client-id: ${SPI_ADMIN_SERVICE_CLIENT_ID}
            client-secret: ${SPI_ADMIN_SERVICE_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            scope: openid, profile, email
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"
        provider:
          keycloak:
            issuer-uri: ${SPI_URI_SERVER}
            user-name-attribute: preferred_username

logging:
  level:
    org.springframework.cloud.gateway: TRACE
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    org.springframework.boot.autoconfigure.web: DEBUG
    redisratelimiter: DEBUG
    reactor.ipc.netty: DEBUG
    reactor.netty: DEBUG
    reactor.netty.http.client: DEBUG
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
    org.springframework.web.reactive.function.client: TRACE
    org.springframework.jdbc.core.JdbcTemplate: DEBUG
