spring:
  jpa:
    open-in-view: true
    properties:
      hibernate:
        cache:
          use_second_level_cache: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
        use_sql_comments: true
    show-sql: true
datasource:
    hikari:
      pool-name: AdminServiceHikariPool
      connection-test-query: SELECT 1
